version: '2'

volumes:
   nextcloud:
   db:

services:
  db:
    image: mariadb:10.5
    networks: 
      - npm
    container_name: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}

  app:
    image: mynextcloud
    container_name: nextcloud
    restart: always
    expose:
      - 8070
    ports:
         - 8070:443
    networks: 
      - npm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./startup_root.sh:/var/www/startup_root.sh
      - ./startup_wdata.sh:/var/www/startup_wdata.sh
      - ./fileshare/:/var/www/fileshare/
      - "D:/PicShare/:/media/share"
      - "D:/github/photos/js:/media/share/js"
      - "D:/github/certs/:/media/share/certs"

    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_CUSTOM_APPS=maps
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M

    cap_add:
      - ALL

networks:
  npm:
    external: true


